server:
  port: 8085
  context-path: /client
spring:
  application:
    name: micro-weather-eureka-client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeOut: 5000
        readTimeOut: 5000