server:
  port: 8086
  context-path: /client-zuul
spring:
  application:
    name: micro-weather-eureka-client-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    city:
      path: /weather-city-server/**
      serviceId: micro-weather-city-client
      stripPrefix: false
    data:
      path: /weather-data-server/**
      serviceId: micro-weather-data-client
      stripPrefix: false