server:
  port: 8087
  context-path: /config-server
spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hblolj/spring-cloud-weather-configs
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/